namespace DeepSeek.Classes;

/// <summary>
/// Chat response
/// </summary>
public class ChatResponse
{
    /// <summary>
    /// The unique identifier for the conversation.
    /// </summary>
    public string? Id { get; set; }

    /// <summary>
    /// A list of choices generated by the model for the completion.
    /// </summary>
    public List<Choice> Choices { get; set; } = [];

    /// <summary>
    /// The name of the model used to generate the completion.
    /// </summary>
    public string? Model { get; set; }

    /// <summary>
    /// The Unix timestamp (in seconds) when the chat completion was created.
    /// </summary>
    public long Created { get; set; }

    /// <summary>
    /// The type of object, which is "chat.completion".
    /// </summary>
    public string Object { get; set; } = "chat.completion";

    /// <summary>
    /// Usage information for the chat completion request.
    /// </summary>
    public Usage? Usage { get; set; }
}