using System.Text.Json.Serialization;

namespace DeepSeek.Classes;

/// <summary>
/// A choice generated by the model.
/// </summary>
public class Choice
{
    [JsonPropertyName("finish_reason")]
    public string? FinishReason { get; set; }

    public long Index { get; set; }

    public Message? Message { get; set; }

    /// <summary>
    /// Log probability information for this choice.
    /// </summary>
    public Logprobs? Logprobs { get; set; }

    /// <summary>
    /// Incremental content returned in streaming mode.
    /// </summary>
    public Message? Delta { get; set; }
}
